name: Update Counts
on:
    workflow_dispatch:
    schedule:
        - cron: '0 0,12 * * *'
permissions:
    contents: write
jobs:
    update:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Prepare Python
              uses: actions/setup-python@v2

            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Checkout code
              uses: actions/checkout@v3

            - name: Update counts
              run: |
                python src/update_counts.py
                git config user.name github-actions
                git config user.email github-actions@github.com
                git add bin/counts.json
                git commit -m "Update counts"
                git push

            - name: Deploy to Render
              env: 
                deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
              run: |
                curl "$deploy_url"